name: Build Tauri Windows App

on:
  push:
    tags:
      - 'v*'   # 每次推送以 'v' 开头的标签（如 v1.0.0）时触发构建
permissions:
  contents: write 

jobs:
  build-tauri-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

          # 缓存 node_modules、cargo 依赖
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-tauri-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend dependencies
        run: npm install

      - name: Build Tauri App (no bundle)
        run: npm run tauri build -- --no-bundle

      - name: Upload green portable exe
        uses: actions/upload-artifact@v4
        with:
          name: tauri-portable
          path: src-tauri/target/release/tauri_demo.exe